name: Build - Prod
on:
  push:
    branches: [ "main" ]
  merge:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: 'npm'
      - run: npm ci
      - run: npm run setApiKey ${{ secrets.PROD_API_URL }} ${{ secrets.PROD_APP_INSIGHT }}
      - run: npm run build --prod
      - run: npm test --if-present
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.PROD_AZURE_TOKEN }}
          action: "upload"
          skip_app_build: true
          skip_api_build: true
          app_location: "dist/ng-pokemon-app"